services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/sleeptracker
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mongodb_data: 